["!local"]
rockTexture = "quark:block/slate"

["emendatusenigmatica:aluminum_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/aluminum"

["emendatusenigmatica:apatite_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/apatite"

["emendatusenigmatica:arcane_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/arcane"

["emendatusenigmatica:bitumen_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/bitumen"

["emendatusenigmatica:certus_quartz_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/certus_quartz"

["emendatusenigmatica:charged_certus_quartz_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/charged_certus_quartz"

["emendatusenigmatica:cinnabar_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cinnabar"

["emendatusenigmatica:coal_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/coal"

["emendatusenigmatica:cobalt_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cobalt"

["emendatusenigmatica:copper_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/copper"

["emendatusenigmatica:diamond_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/diamond"

["emendatusenigmatica:dimensional_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/dimensional"

["emendatusenigmatica:emerald_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/emerald"

["emendatusenigmatica:fluorite_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/fluorite"

["emendatusenigmatica:gold_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/gold"

["emendatusenigmatica:iridium_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iridium"

["emendatusenigmatica:iron_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iron"

["emendatusenigmatica:lapis_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lapis"

["emendatusenigmatica:lead_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lead"

["emendatusenigmatica:nickel_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/nickel"

["emendatusenigmatica:osmium_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/osmium"

["emendatusenigmatica:peridot_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/peridot"

["emendatusenigmatica:potassium_nitrate_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/potassium_nitrate"

["emendatusenigmatica:redstone_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/redstone"

["emendatusenigmatica:ruby_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/ruby"

["emendatusenigmatica:sapphire_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sapphire"

["emendatusenigmatica:silver_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/silver"

["emendatusenigmatica:sulfur_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sulfur"

["emendatusenigmatica:tin_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/tin"

["emendatusenigmatica:uranium_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/uranium"

["emendatusenigmatica:zinc_slate_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/zinc"