["!local"]
rockTexture = "minecraft:block/andesite"

["emendatusenigmatica:aluminum_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/aluminum"

["emendatusenigmatica:apatite_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/apatite"

["emendatusenigmatica:arcane_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/arcane"

["emendatusenigmatica:bitumen_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/bitumen"

["emendatusenigmatica:certus_quartz_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/certus_quartz"
maxOreLayerColorDiff = 17

["emendatusenigmatica:charged_certus_quartz_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/charged_certus_quartz"

["emendatusenigmatica:cinnabar_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cinnabar"

["emendatusenigmatica:coal_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/coal"

["emendatusenigmatica:cobalt_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cobalt"

["emendatusenigmatica:copper_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/copper"

["emendatusenigmatica:diamond_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/diamond"

["emendatusenigmatica:dimensional_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/dimensional"

["emendatusenigmatica:emerald_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/emerald"

["emendatusenigmatica:fluorite_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/fluorite"

["emendatusenigmatica:gold_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/gold"

["emendatusenigmatica:iridium_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iridium"

["emendatusenigmatica:iron_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iron"

["emendatusenigmatica:lapis_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lapis"

["emendatusenigmatica:lead_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lead"

["emendatusenigmatica:nickel_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/nickel"
maxOreLayerColorDiff = 37

["emendatusenigmatica:osmium_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/osmium"

["emendatusenigmatica:peridot_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/peridot"

["emendatusenigmatica:potassium_nitrate_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/potassium_nitrate"

["emendatusenigmatica:redstone_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/redstone"

["emendatusenigmatica:ruby_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/ruby"

["emendatusenigmatica:sapphire_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sapphire"

["emendatusenigmatica:silver_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/silver"

["emendatusenigmatica:sulfur_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sulfur"

["emendatusenigmatica:tin_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/tin"

["emendatusenigmatica:uranium_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/uranium"

["emendatusenigmatica:zinc_andesite_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/zinc"