["!local"]
rockTexture = "create:block/palettes/weathered_limestone/plain"

["emendatusenigmatica:aluminum_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/aluminum"

["emendatusenigmatica:apatite_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/apatite"

["emendatusenigmatica:arcane_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/arcane"

["emendatusenigmatica:bitumen_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/bitumen"

["emendatusenigmatica:certus_quartz_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/certus_quartz"

["emendatusenigmatica:charged_certus_quartz_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/charged_certus_quartz"

["emendatusenigmatica:cinnabar_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cinnabar"

["emendatusenigmatica:coal_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/coal"

["emendatusenigmatica:cobalt_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cobalt"

["emendatusenigmatica:copper_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/copper"

["emendatusenigmatica:diamond_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/diamond"

["emendatusenigmatica:dimensional_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/dimensional"

["emendatusenigmatica:emerald_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/emerald"

["emendatusenigmatica:fluorite_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/fluorite"

["emendatusenigmatica:gold_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/gold"

["emendatusenigmatica:iridium_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iridium"

["emendatusenigmatica:iron_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iron"

["emendatusenigmatica:lapis_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lapis"

["emendatusenigmatica:lead_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lead"

["emendatusenigmatica:nickel_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/nickel"

["emendatusenigmatica:osmium_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/osmium"

["emendatusenigmatica:peridot_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/peridot"

["emendatusenigmatica:potassium_nitrate_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/potassium_nitrate"

["emendatusenigmatica:redstone_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/redstone"

["emendatusenigmatica:ruby_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/ruby"

["emendatusenigmatica:sapphire_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sapphire"

["emendatusenigmatica:silver_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/silver"

["emendatusenigmatica:sulfur_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sulfur"

["emendatusenigmatica:tin_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/tin"

["emendatusenigmatica:uranium_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/uranium"

["emendatusenigmatica:zinc_weathered_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/zinc"