["!local"]
rockTexture = "create:block/palettes/gabbro/plain"

["emendatusenigmatica:aluminum_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/aluminum"
maxOreLayerColorDiff = 25

["emendatusenigmatica:apatite_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/apatite"

["emendatusenigmatica:arcane_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/arcane"

["emendatusenigmatica:bitumen_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/bitumen"

["emendatusenigmatica:certus_quartz_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/certus_quartz"

["emendatusenigmatica:charged_certus_quartz_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/charged_certus_quartz"

["emendatusenigmatica:cinnabar_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cinnabar"

["emendatusenigmatica:coal_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/coal"

["emendatusenigmatica:cobalt_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cobalt"

["emendatusenigmatica:copper_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/copper"

["emendatusenigmatica:diamond_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/diamond"

["emendatusenigmatica:dimensional_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/dimensional"

["emendatusenigmatica:emerald_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/emerald"

["emendatusenigmatica:fluorite_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/fluorite"

["emendatusenigmatica:gold_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/gold"

["emendatusenigmatica:iridium_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iridium"

["emendatusenigmatica:iron_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iron"
maxOreLayerColorDiff = 28

["emendatusenigmatica:lapis_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lapis"

["emendatusenigmatica:lead_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lead"

["emendatusenigmatica:nickel_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/nickel"
maxOreLayerColorDiff = 25

["emendatusenigmatica:osmium_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/osmium"

["emendatusenigmatica:peridot_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/peridot"

["emendatusenigmatica:potassium_nitrate_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/potassium_nitrate"

["emendatusenigmatica:redstone_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/redstone"

["emendatusenigmatica:ruby_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/ruby"

["emendatusenigmatica:sapphire_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sapphire"

["emendatusenigmatica:silver_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/silver"

["emendatusenigmatica:sulfur_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sulfur"

["emendatusenigmatica:tin_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/tin"

["emendatusenigmatica:uranium_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/uranium"

["emendatusenigmatica:zinc_gabbro_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/zinc"