["!local"]
rockTexture = "quark:block/jasper"

["emendatusenigmatica:aluminum_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/aluminum"

["emendatusenigmatica:apatite_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/apatite"

["emendatusenigmatica:arcane_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/arcane"

["emendatusenigmatica:bitumen_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/bitumen"

["emendatusenigmatica:certus_quartz_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/certus_quartz"

["emendatusenigmatica:charged_certus_quartz_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/charged_certus_quartz"

["emendatusenigmatica:cinnabar_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cinnabar"

["emendatusenigmatica:coal_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/coal"

["emendatusenigmatica:cobalt_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cobalt"

["emendatusenigmatica:copper_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/copper"

["emendatusenigmatica:diamond_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/diamond"

["emendatusenigmatica:dimensional_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/dimensional"

["emendatusenigmatica:emerald_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/emerald"

["emendatusenigmatica:fluorite_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/fluorite"

["emendatusenigmatica:gold_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/gold"

["emendatusenigmatica:iridium_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iridium"

["emendatusenigmatica:iron_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iron"

["emendatusenigmatica:lapis_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lapis"

["emendatusenigmatica:lead_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lead"

["emendatusenigmatica:nickel_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/nickel"

["emendatusenigmatica:osmium_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/osmium"

["emendatusenigmatica:peridot_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/peridot"

["emendatusenigmatica:potassium_nitrate_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/potassium_nitrate"

["emendatusenigmatica:redstone_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/redstone"

["emendatusenigmatica:ruby_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/ruby"

["emendatusenigmatica:sapphire_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sapphire"

["emendatusenigmatica:silver_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/silver"

["emendatusenigmatica:sulfur_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sulfur"

["emendatusenigmatica:tin_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/tin"

["emendatusenigmatica:uranium_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/uranium"

["emendatusenigmatica:zinc_jasper_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/zinc"