["!local"]
rockTexture = "create:block/palettes/limestone/plain"

["emendatusenigmatica:aluminum_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/aluminum"

["emendatusenigmatica:apatite_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/apatite"

["emendatusenigmatica:arcane_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/arcane"

["emendatusenigmatica:bitumen_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/bitumen"

["emendatusenigmatica:certus_quartz_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/certus_quartz"

["emendatusenigmatica:charged_certus_quartz_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/charged_certus_quartz"

["emendatusenigmatica:cinnabar_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cinnabar"

["emendatusenigmatica:coal_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/coal"

["emendatusenigmatica:cobalt_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/cobalt"

["emendatusenigmatica:copper_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/copper"

["emendatusenigmatica:diamond_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/diamond"

["emendatusenigmatica:dimensional_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/dimensional"

["emendatusenigmatica:emerald_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/emerald"

["emendatusenigmatica:fluorite_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/fluorite"

["emendatusenigmatica:gold_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/gold"

["emendatusenigmatica:iridium_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iridium"

["emendatusenigmatica:iron_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/iron"

["emendatusenigmatica:lapis_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lapis"

["emendatusenigmatica:lead_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/lead"

["emendatusenigmatica:nickel_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/nickel"
maxOreLayerColorDiff = 0

["emendatusenigmatica:osmium_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/osmium"

["emendatusenigmatica:peridot_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/peridot"

["emendatusenigmatica:potassium_nitrate_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/potassium_nitrate"
maxOreLayerColorDiff = 20

["emendatusenigmatica:redstone_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/redstone"

["emendatusenigmatica:ruby_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/ruby"

["emendatusenigmatica:sapphire_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sapphire"

["emendatusenigmatica:silver_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/silver"

["emendatusenigmatica:sulfur_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/sulfur"

["emendatusenigmatica:tin_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/tin"
maxOreLayerColorDiff = 14

["emendatusenigmatica:uranium_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/uranium"

["emendatusenigmatica:zinc_c_limestone_ore"]
oreTexture = "emendatusenigmatica:blocks/overlays/zinc"
maxOreLayerColorDiff = 20